name: PR review reminders
on:
 schedule:
    # Send notification every 2 hours during working hours on weekdays 
    - cron: "0,15,30,45 16-22 * * 1-5"
jobs:
  pr-reviews-reminder:
   runs-on: ubuntu-latest
   steps:
   - uses: DavideViolante/pr-reviews-reminder-action@v1.6.1
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
       webhook-url: ${{ secrets.TEAMS_WEBHOOK }}
       provider: 'msteams'
